services:
  artox_lab_clarc.command_bus:
    class: \ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\CommandBus\CommandBus
    arguments: ['@command.bus']

  artox_lab_clarc.command_bus.validation:
    class: 'ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\CommandBus\Middleware\ValidationMiddleware'
    arguments:
      - '@validator'

  ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\CommandBus\CommandBusInterface: '@artox_lab_clarc.command_bus'

  api_exception_subscriber:
    class: ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\UI\API\EventListeners\ExceptionSubscriber
    arguments: ['@translator']
    tags:
      - { name: kernel.event_subscriber }

  ArtoxLab\Bundle\ClarcBundle\Command\Maker\:
    resource: '../../Command/Maker/*'
    exclude: '../../Command/Maker/{AbstractMaker.php}'
    tags: ['maker.command']

  ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\UI\API\Requests\RequestResolver:
    arguments:
      - '@validator'
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  League\Fractal\Serializer\Serializer:
    class: \ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\UI\API\Transformers\Serializers\NullObjectArraySerializer

  ArtoxLab\Bundle\ClarcBundle\Core\Interfaces\UI\API\Controllers\:
    resource: '../../Core/Interfaces/UI/API/Controllers/'
    tags: ['controller.service_arguments']
